import type { RrpiSeedRecord } from "@/lib/pricing/rrpi-calibration";

// Generated by scripts/update-rrpi-calibration.mjs from Statistics Canada table 18-10-0286-01.
// Empty by default so the app uses the curated fallback seed in rrpi-calibration.ts.
export const RRPI_GENERATED_SEED: RrpiSeedRecord[] = [];
